enum Icon {


    _500PX = '<i class="fa fa-500px"></i>',
    ADDRESS_BOOK = '<i class="fa fa-address-book"></i>',
    ADDRESS_BOOK_O = '<i class="fa fa-address-book-o"></i>',
    ADDRESS_CARD = '<i class="fa fa-address-card"></i>',
    ADDRESS_CARD_O = '<i class="fa fa-address-card-o"></i>',
    ADJUST = '<i class="fa fa-adjust"></i>',
    ADN = '<i class="fa fa-adn"></i>',
    ALIGN_CENTER = '<i class="fa fa-align-center"></i>',
    ALIGN_JUSTIFY = '<i class="fa fa-align-justify"></i>',
    ALIGN_LEFT = '<i class="fa fa-align-left"></i>',
    ALIGN_RIGHT = '<i class="fa fa-align-right"></i>',
    AMAZON = '<i class="fa fa-amazon"></i>',
    AMBULANCE = '<i class="fa fa-ambulance"></i>',
    AMERICAN_SIGN_LANGUAGE_INTERPRETING = '<i class="fa fa-american-sign-language-interpreting"></i>',
    ANCHOR = '<i class="fa fa-anchor"></i>',
    ANDROID = '<i class="fa fa-android"></i>',
    ANGELLIST = '<i class="fa fa-angellist"></i>',
    ANGLE_DOUBLE_DOWN = '<i class="fa fa-angle-double-down"></i>',
    ANGLE_DOUBLE_LEFT = '<i class="fa fa-angle-double-left"></i>',
    ANGLE_DOUBLE_RIGHT = '<i class="fa fa-angle-double-right"></i>',
    ANGLE_DOUBLE_UP = '<i class="fa fa-angle-double-up"></i>',
    ANGLE_DOWN = '<i class="fa fa-angle-down"></i>',
    ANGLE_LEFT = '<i class="fa fa-angle-left"></i>',
    ANGLE_RIGHT = '<i class="fa fa-angle-right"></i>',
    ANGLE_UP = '<i class="fa fa-angle-up"></i>',
    APPLE = '<i class="fa fa-apple"></i>',
    ARCHIVE = '<i class="fa fa-archive"></i>',
    AREA_CHART = '<i class="fa fa-area-chart"></i>',
    ARROW_CIRCLE_DOWN = '<i class="fa fa-arrow-circle-down"></i>',
    ARROW_CIRCLE_LEFT = '<i class="fa fa-arrow-circle-left"></i>',
    ARROW_CIRCLE_O_DOWN = '<i class="fa fa-arrow-circle-o-down"></i>',
    ARROW_CIRCLE_O_LEFT = '<i class="fa fa-arrow-circle-o-left"></i>',
    ARROW_CIRCLE_O_RIGHT = '<i class="fa fa-arrow-circle-o-right"></i>',
    ARROW_CIRCLE_O_UP = '<i class="fa fa-arrow-circle-o-up"></i>',
    ARROW_CIRCLE_RIGHT = '<i class="fa fa-arrow-circle-right"></i>',
    ARROW_CIRCLE_UP = '<i class="fa fa-arrow-circle-up"></i>',
    ARROW_DOWN = '<i class="fa fa-arrow-down"></i>',
    ARROW_LEFT = '<i class="fa fa-arrow-left"></i>',
    ARROW_RIGHT = '<i class="fa fa-arrow-right"></i>',
    ARROW_UP = '<i class="fa fa-arrow-up"></i>',
    ARROWS = '<i class="fa fa-arrows"></i>',
    ARROWS_ALT = '<i class="fa fa-arrows-alt"></i>',
    ARROWS_H = '<i class="fa fa-arrows-h"></i>',
    ARROWS_V = '<i class="fa fa-arrows-v"></i>',
    ASL_INTERPRETING = '<i class="fa fa-asl-interpreting (alias)"></i>',
    ASSISTIVE_LISTENING_SYSTEMS = '<i class="fa fa-assistive-listening-systems"></i>',
    ASTERISK = '<i class="fa fa-asterisk"></i>',
    AT = '<i class="fa fa-at"></i>',
    AUDIO_DESCRIPTION = '<i class="fa fa-audio-description"></i>',
    AUTOMOBILE = '<i class="fa fa-automobile (alias)"></i>',
    BACKWARD = '<i class="fa fa-backward"></i>',
    BALANCE_SCALE = '<i class="fa fa-balance-scale"></i>',
    BAN = '<i class="fa fa-ban"></i>',
    BANDCAMP = '<i class="fa fa-bandcamp"></i>',
    BANK = '<i class="fa fa-bank (alias)"></i>',
    BAR_CHART = '<i class="fa fa-bar-chart"></i>',
    BAR_CHART_O = '<i class="fa fa-bar-chart-o (alias)"></i>',
    BARCODE = '<i class="fa fa-barcode"></i>',
    BARS = '<i class="fa fa-bars"></i>',
    BATH = '<i class="fa fa-bath"></i>',
    BATHTUB = '<i class="fa fa-bathtub (alias)"></i>',
    BATTERY = '<i class="fa fa-battery (alias)"></i>',
    BATTERY_0 = '<i class="fa fa-battery-0 (alias)"></i>',
    BATTERY_1 = '<i class="fa fa-battery-1 (alias)"></i>',
    BATTERY_2 = '<i class="fa fa-battery-2 (alias)"></i>',
    BATTERY_3 = '<i class="fa fa-battery-3 (alias)"></i>',
    BATTERY_4 = '<i class="fa fa-battery-4 (alias)"></i>',
    BATTERY_EMPTY = '<i class="fa fa-battery-empty"></i>',
    BATTERY_FULL = '<i class="fa fa-battery-full"></i>',
    BATTERY_HALF = '<i class="fa fa-battery-half"></i>',
    BATTERY_QUARTER = '<i class="fa fa-battery-quarter"></i>',
    BATTERY_THREE_QUARTERS = '<i class="fa fa-battery-three-quarters"></i>',
    BED = '<i class="fa fa-bed"></i>',
    BEER = '<i class="fa fa-beer"></i>',
    BEHANCE = '<i class="fa fa-behance"></i>',
    BEHANCE_SQUARE = '<i class="fa fa-behance-square"></i>',
    BELL = '<i class="fa fa-bell"></i>',
    BELL_O = '<i class="fa fa-bell-o"></i>',
    BELL_SLASH = '<i class="fa fa-bell-slash"></i>',
    BELL_SLASH_O = '<i class="fa fa-bell-slash-o"></i>',
    BICYCLE = '<i class="fa fa-bicycle"></i>',
    BINOCULARS = '<i class="fa fa-binoculars"></i>',
    BIRTHDAY_CAKE = '<i class="fa fa-birthday-cake"></i>',
    BITBUCKET = '<i class="fa fa-bitbucket"></i>',
    BITBUCKET_SQUARE = '<i class="fa fa-bitbucket-square"></i>',
    BITCOIN = '<i class="fa fa-bitcoin (alias)"></i>',
    BLACK_TIE = '<i class="fa fa-black-tie"></i>',
    BLIND = '<i class="fa fa-blind"></i>',
    BLUETOOTH = '<i class="fa fa-bluetooth"></i>',
    BLUETOOTH_B = '<i class="fa fa-bluetooth-b"></i>',
    BOLD = '<i class="fa fa-bold"></i>',
    BOLT = '<i class="fa fa-bolt"></i>',
    BOMB = '<i class="fa fa-bomb"></i>',
    BOOK = '<i class="fa fa-book"></i>',
    BOOKMARK = '<i class="fa fa-bookmark"></i>',
    BOOKMARK_O = '<i class="fa fa-bookmark-o"></i>',
    BRAILLE = '<i class="fa fa-braille"></i>',
    BRIEFCASE = '<i class="fa fa-briefcase"></i>',
    BTC = '<i class="fa fa-btc"></i>',
    BUG = '<i class="fa fa-bug"></i>',
    BUILDING = '<i class="fa fa-building"></i>',
    BUILDING_O = '<i class="fa fa-building-o"></i>',
    BULLHORN = '<i class="fa fa-bullhorn"></i>',
    BULLSEYE = '<i class="fa fa-bullseye"></i>',
    BUS = '<i class="fa fa-bus"></i>',
    BUYSELLADS = '<i class="fa fa-buysellads"></i>',
    CAB = '<i class="fa fa-cab (alias)"></i>',
    CALCULATOR = '<i class="fa fa-calculator"></i>',
    CALENDAR = '<i class="fa fa-calendar"></i>',
    CALENDAR_CHECK_O = '<i class="fa fa-calendar-check-o"></i>',
    CALENDAR_MINUS_O = '<i class="fa fa-calendar-minus-o"></i>',
    CALENDAR_O = '<i class="fa fa-calendar-o"></i>',
    CALENDAR_PLUS_O = '<i class="fa fa-calendar-plus-o"></i>',
    CALENDAR_TIMES_O = '<i class="fa fa-calendar-times-o"></i>',
    CAMERA = '<i class="fa fa-camera"></i>',
    CAMERA_RETRO = '<i class="fa fa-camera-retro"></i>',
    CAR = '<i class="fa fa-car"></i>',
    CARET_DOWN = '<i class="fa fa-caret-down"></i>',
    CARET_LEFT = '<i class="fa fa-caret-left"></i>',
    CARET_RIGHT = '<i class="fa fa-caret-right"></i>',
    CARET_SQUARE_O_DOWN = '<i class="fa fa-caret-square-o-down"></i>',
    CARET_SQUARE_O_LEFT = '<i class="fa fa-caret-square-o-left"></i>',
    CARET_SQUARE_O_RIGHT = '<i class="fa fa-caret-square-o-right"></i>',
    CARET_SQUARE_O_UP = '<i class="fa fa-caret-square-o-up"></i>',
    CARET_UP = '<i class="fa fa-caret-up"></i>',
    CART_ARROW_DOWN = '<i class="fa fa-cart-arrow-down"></i>',
    CART_PLUS = '<i class="fa fa-cart-plus"></i>',
    CC = '<i class="fa fa-cc"></i>',
    CC_AMEX = '<i class="fa fa-cc-amex"></i>',
    CC_DINERS_CLUB = '<i class="fa fa-cc-diners-club"></i>',
    CC_DISCOVER = '<i class="fa fa-cc-discover"></i>',
    CC_JCB = '<i class="fa fa-cc-jcb"></i>',
    CC_MASTERCARD = '<i class="fa fa-cc-mastercard"></i>',
    CC_PAYPAL = '<i class="fa fa-cc-paypal"></i>',
    CC_STRIPE = '<i class="fa fa-cc-stripe"></i>',
    CC_VISA = '<i class="fa fa-cc-visa"></i>',
    CERTIFICATE = '<i class="fa fa-certificate"></i>',
    CHAIN = '<i class="fa fa-chain (alias)"></i>',
    CHAIN_BROKEN = '<i class="fa fa-chain-broken"></i>',
    CHECK = '<i class="fa fa-check"></i>',
    CHECK_CIRCLE = '<i class="fa fa-check-circle"></i>',
    CHECK_CIRCLE_O = '<i class="fa fa-check-circle-o"></i>',
    CHECK_SQUARE = '<i class="fa fa-check-square"></i>',
    CHECK_SQUARE_O = '<i class="fa fa-check-square-o"></i>',
    CHEVRON_CIRCLE_DOWN = '<i class="fa fa-chevron-circle-down"></i>',
    CHEVRON_CIRCLE_LEFT = '<i class="fa fa-chevron-circle-left"></i>',
    CHEVRON_CIRCLE_RIGHT = '<i class="fa fa-chevron-circle-right"></i>',
    CHEVRON_CIRCLE_UP = '<i class="fa fa-chevron-circle-up"></i>',
    CHEVRON_DOWN = '<i class="fa fa-chevron-down"></i>',
    CHEVRON_LEFT = '<i class="fa fa-chevron-left"></i>',
    CHEVRON_RIGHT = '<i class="fa fa-chevron-right"></i>',
    CHEVRON_UP = '<i class="fa fa-chevron-up"></i>',
    CHILD = '<i class="fa fa-child"></i>',
    CHROME = '<i class="fa fa-chrome"></i>',
    CIRCLE = '<i class="fa fa-circle"></i>',
    CIRCLE_O = '<i class="fa fa-circle-o"></i>',
    CIRCLE_O_NOTCH = '<i class="fa fa-circle-o-notch"></i>',
    CIRCLE_THIN = '<i class="fa fa-circle-thin"></i>',
    CLIPBOARD = '<i class="fa fa-clipboard"></i>',
    CLOCK_O = '<i class="fa fa-clock-o"></i>',
    CLONE = '<i class="fa fa-clone"></i>',
    CLOSE = '<i class="fa fa-close (alias)"></i>',
    CLOUD = '<i class="fa fa-cloud"></i>',
    CLOUD_DOWNLOAD = '<i class="fa fa-cloud-download"></i>',
    CLOUD_UPLOAD = '<i class="fa fa-cloud-upload"></i>',
    CNY = '<i class="fa fa-cny (alias)"></i>',
    CODE = '<i class="fa fa-code"></i>',
    CODE_FORK = '<i class="fa fa-code-fork"></i>',
    CODEPEN = '<i class="fa fa-codepen"></i>',
    CODIEPIE = '<i class="fa fa-codiepie"></i>',
    COFFEE = '<i class="fa fa-coffee"></i>',
    COG = '<i class="fa fa-cog"></i>',
    COGS = '<i class="fa fa-cogs"></i>',
    COLUMNS = '<i class="fa fa-columns"></i>',
    COMMENT = '<i class="fa fa-comment"></i>',
    COMMENT_O = '<i class="fa fa-comment-o"></i>',
    COMMENTING = '<i class="fa fa-commenting"></i>',
    COMMENTING_O = '<i class="fa fa-commenting-o"></i>',
    COMMENTS = '<i class="fa fa-comments"></i>',
    COMMENTS_O = '<i class="fa fa-comments-o"></i>',
    COMPASS = '<i class="fa fa-compass"></i>',
    COMPRESS = '<i class="fa fa-compress"></i>',
    CONNECTDEVELOP = '<i class="fa fa-connectdevelop"></i>',
    CONTAO = '<i class="fa fa-contao"></i>',
    COPY = '<i class="fa fa-copy (alias)"></i>',
    COPYRIGHT = '<i class="fa fa-copyright"></i>',
    CREATIVE_COMMONS = '<i class="fa fa-creative-commons"></i>',
    CREDIT_CARD = '<i class="fa fa-credit-card"></i>',
    CREDIT_CARD_ALT = '<i class="fa fa-credit-card-alt"></i>',
    CROP = '<i class="fa fa-crop"></i>',
    CROSSHAIRS = '<i class="fa fa-crosshairs"></i>',
    CSS3 = '<i class="fa fa-css3"></i>',
    CUBE = '<i class="fa fa-cube"></i>',
    CUBES = '<i class="fa fa-cubes"></i>',
    CUT = '<i class="fa fa-cut (alias)"></i>',
    CUTLERY = '<i class="fa fa-cutlery"></i>',
    DASHBOARD = '<i class="fa fa-dashboard (alias)"></i>',
    DASHCUBE = '<i class="fa fa-dashcube"></i>',
    DATABASE = '<i class="fa fa-database"></i>',
    DEAF = '<i class="fa fa-deaf"></i>',
    DEAFNESS = '<i class="fa fa-deafness (alias)"></i>',
    DEDENT = '<i class="fa fa-dedent (alias)"></i>',
    DELICIOUS = '<i class="fa fa-delicious"></i>',
    DESKTOP = '<i class="fa fa-desktop"></i>',
    DEVIANTART = '<i class="fa fa-deviantart"></i>',
    DIAMOND = '<i class="fa fa-diamond"></i>',
    DIGG = '<i class="fa fa-digg"></i>',
    DOLLAR = '<i class="fa fa-dollar (alias)"></i>',
    DOT_CIRCLE_O = '<i class="fa fa-dot-circle-o"></i>',
    DOWNLOAD = '<i class="fa fa-download"></i>',
    DRIBBBLE = '<i class="fa fa-dribbble"></i>',
    DRIVERS_LICENSE = '<i class="fa fa-drivers-license (alias)"></i>',
    DRIVERS_LICENSE_O = '<i class="fa fa-drivers-license-o (alias)"></i>',
    DROPBOX = '<i class="fa fa-dropbox"></i>',
    DRUPAL = '<i class="fa fa-drupal"></i>',
    EDGE = '<i class="fa fa-edge"></i>',
    EDIT = '<i class="fa fa-edit (alias)"></i>',
    EERCAST = '<i class="fa fa-eercast"></i>',
    EJECT = '<i class="fa fa-eject"></i>',
    ELLIPSIS_H = '<i class="fa fa-ellipsis-h"></i>',
    ELLIPSIS_V = '<i class="fa fa-ellipsis-v"></i>',
    EMPIRE = '<i class="fa fa-empire"></i>',
    ENVELOPE = '<i class="fa fa-envelope"></i>',
    ENVELOPE_O = '<i class="fa fa-envelope-o"></i>',
    ENVELOPE_OPEN = '<i class="fa fa-envelope-open"></i>',
    ENVELOPE_OPEN_O = '<i class="fa fa-envelope-open-o"></i>',
    ENVELOPE_SQUARE = '<i class="fa fa-envelope-square"></i>',
    ENVIRA = '<i class="fa fa-envira"></i>',
    ERASER = '<i class="fa fa-eraser"></i>',
    ETSY = '<i class="fa fa-etsy"></i>',
    EUR = '<i class="fa fa-eur"></i>',
    EURO = '<i class="fa fa-euro (alias)"></i>',
    EXCHANGE = '<i class="fa fa-exchange"></i>',
    EXCLAMATION = '<i class="fa fa-exclamation"></i>',
    EXCLAMATION_CIRCLE = '<i class="fa fa-exclamation-circle"></i>',
    EXCLAMATION_TRIANGLE = '<i class="fa fa-exclamation-triangle"></i>',
    EXPAND = '<i class="fa fa-expand"></i>',
    EXPEDITEDSSL = '<i class="fa fa-expeditedssl"></i>',
    EXTERNAL_LINK = '<i class="fa fa-external-link"></i>',
    EXTERNAL_LINK_SQUARE = '<i class="fa fa-external-link-square"></i>',
    EYE = '<i class="fa fa-eye"></i>',
    EYE_SLASH = '<i class="fa fa-eye-slash"></i>',
    EYEDROPPER = '<i class="fa fa-eyedropper"></i>',
    FA = '<i class="fa fa-fa (alias)"></i>',
    FACEBOOK = '<i class="fa fa-facebook"></i>',
    FACEBOOK_F = '<i class="fa fa-facebook-f (alias)"></i>',
    FACEBOOK_OFFICIAL = '<i class="fa fa-facebook-official"></i>',
    FACEBOOK_SQUARE = '<i class="fa fa-facebook-square"></i>',
    FAST_BACKWARD = '<i class="fa fa-fast-backward"></i>',
    FAST_FORWARD = '<i class="fa fa-fast-forward"></i>',
    FAX = '<i class="fa fa-fax"></i>',
    FEED = '<i class="fa fa-feed (alias)"></i>',
    FEMALE = '<i class="fa fa-female"></i>',
    FIGHTER_JET = '<i class="fa fa-fighter-jet"></i>',
    FILE = '<i class="fa fa-file"></i>',
    FILE_ARCHIVE_O = '<i class="fa fa-file-archive-o"></i>',
    FILE_AUDIO_O = '<i class="fa fa-file-audio-o"></i>',
    FILE_CODE_O = '<i class="fa fa-file-code-o"></i>',
    FILE_EXCEL_O = '<i class="fa fa-file-excel-o"></i>',
    FILE_IMAGE_O = '<i class="fa fa-file-image-o"></i>',
    FILE_MOVIE_O = '<i class="fa fa-file-movie-o (alias)"></i>',
    FILE_O = '<i class="fa fa-file-o"></i>',
    FILE_PDF_O = '<i class="fa fa-file-pdf-o"></i>',
    FILE_PHOTO_O = '<i class="fa fa-file-photo-o (alias)"></i>',
    FILE_PICTURE_O = '<i class="fa fa-file-picture-o (alias)"></i>',
    FILE_POWERPOINT_O = '<i class="fa fa-file-powerpoint-o"></i>',
    FILE_SOUND_O = '<i class="fa fa-file-sound-o (alias)"></i>',
    FILE_TEXT = '<i class="fa fa-file-text"></i>',
    FILE_TEXT_O = '<i class="fa fa-file-text-o"></i>',
    FILE_VIDEO_O = '<i class="fa fa-file-video-o"></i>',
    FILE_WORD_O = '<i class="fa fa-file-word-o"></i>',
    FILE_ZIP_O = '<i class="fa fa-file-zip-o (alias)"></i>',
    FILES_O = '<i class="fa fa-files-o"></i>',
    FILM = '<i class="fa fa-film"></i>',
    FILTER = '<i class="fa fa-filter"></i>',
    FIRE = '<i class="fa fa-fire"></i>',
    FIRE_EXTINGUISHER = '<i class="fa fa-fire-extinguisher"></i>',
    FIREFOX = '<i class="fa fa-firefox"></i>',
    FIRST_ORDER = '<i class="fa fa-first-order"></i>',
    FLAG = '<i class="fa fa-flag"></i>',
    FLAG_CHECKERED = '<i class="fa fa-flag-checkered"></i>',
    FLAG_O = '<i class="fa fa-flag-o"></i>',
    FLASH = '<i class="fa fa-flash (alias)"></i>',
    FLASK = '<i class="fa fa-flask"></i>',
    FLICKR = '<i class="fa fa-flickr"></i>',
    FLOPPY_O = '<i class="fa fa-floppy-o"></i>',
    FOLDER = '<i class="fa fa-folder"></i>',
    FOLDER_O = '<i class="fa fa-folder-o"></i>',
    FOLDER_OPEN = '<i class="fa fa-folder-open"></i>',
    FOLDER_OPEN_O = '<i class="fa fa-folder-open-o"></i>',
    FONT = '<i class="fa fa-font"></i>',
    FONT_AWESOME = '<i class="fa fa-font-awesome"></i>',
    FONTICONS = '<i class="fa fa-fonticons"></i>',
    FORT_AWESOME = '<i class="fa fa-fort-awesome"></i>',
    FORUMBEE = '<i class="fa fa-forumbee"></i>',
    FORWARD = '<i class="fa fa-forward"></i>',
    FOURSQUARE = '<i class="fa fa-foursquare"></i>',
    FREE_CODE_CAMP = '<i class="fa fa-free-code-camp"></i>',
    FROWN_O = '<i class="fa fa-frown-o"></i>',
    FUTBOL_O = '<i class="fa fa-futbol-o"></i>',
    GAMEPAD = '<i class="fa fa-gamepad"></i>',
    GAVEL = '<i class="fa fa-gavel"></i>',
    GBP = '<i class="fa fa-gbp"></i>',
    GE = '<i class="fa fa-ge (alias)"></i>',
    GEAR = '<i class="fa fa-gear (alias)"></i>',
    GEARS = '<i class="fa fa-gears (alias)"></i>',
    GENDERLESS = '<i class="fa fa-genderless"></i>',
    GET_POCKET = '<i class="fa fa-get-pocket"></i>',
    GG = '<i class="fa fa-gg"></i>',
    GG_CIRCLE = '<i class="fa fa-gg-circle"></i>',
    GIFT = '<i class="fa fa-gift"></i>',
    GIT = '<i class="fa fa-git"></i>',
    GIT_SQUARE = '<i class="fa fa-git-square"></i>',
    GITHUB = '<i class="fa fa-github"></i>',
    GITHUB_ALT = '<i class="fa fa-github-alt"></i>',
    GITHUB_SQUARE = '<i class="fa fa-github-square"></i>',
    GITLAB = '<i class="fa fa-gitlab"></i>',
    GITTIP = '<i class="fa fa-gittip (alias)"></i>',
    GLASS = '<i class="fa fa-glass"></i>',
    GLIDE = '<i class="fa fa-glide"></i>',
    GLIDE_G = '<i class="fa fa-glide-g"></i>',
    GLOBE = '<i class="fa fa-globe"></i>',
    GOOGLE = '<i class="fa fa-google"></i>',
    GOOGLE_PLUS = '<i class="fa fa-google-plus"></i>',
    GOOGLE_PLUS_CIRCLE = '<i class="fa fa-google-plus-circle (alias)"></i>',
    GOOGLE_PLUS_OFFICIAL = '<i class="fa fa-google-plus-official"></i>',
    GOOGLE_PLUS_SQUARE = '<i class="fa fa-google-plus-square"></i>',
    GOOGLE_WALLET = '<i class="fa fa-google-wallet"></i>',
    GRADUATION_CAP = '<i class="fa fa-graduation-cap"></i>',
    GRATIPAY = '<i class="fa fa-gratipay"></i>',
    GRAV = '<i class="fa fa-grav"></i>',
    GROUP = '<i class="fa fa-group (alias)"></i>',
    H_SQUARE = '<i class="fa fa-h-square"></i>',
    HACKER_NEWS = '<i class="fa fa-hacker-news"></i>',
    HAND_GRAB_O = '<i class="fa fa-hand-grab-o (alias)"></i>',
    HAND_LIZARD_O = '<i class="fa fa-hand-lizard-o"></i>',
    HAND_O_DOWN = '<i class="fa fa-hand-o-down"></i>',
    HAND_O_LEFT = '<i class="fa fa-hand-o-left"></i>',
    HAND_O_RIGHT = '<i class="fa fa-hand-o-right"></i>',
    HAND_O_UP = '<i class="fa fa-hand-o-up"></i>',
    HAND_PAPER_O = '<i class="fa fa-hand-paper-o"></i>',
    HAND_PEACE_O = '<i class="fa fa-hand-peace-o"></i>',
    HAND_POINTER_O = '<i class="fa fa-hand-pointer-o"></i>',
    HAND_ROCK_O = '<i class="fa fa-hand-rock-o"></i>',
    HAND_SCISSORS_O = '<i class="fa fa-hand-scissors-o"></i>',
    HAND_SPOCK_O = '<i class="fa fa-hand-spock-o"></i>',
    HAND_STOP_O = '<i class="fa fa-hand-stop-o (alias)"></i>',
    HANDSHAKE_O = '<i class="fa fa-handshake-o"></i>',
    HARD_OF_HEARING = '<i class="fa fa-hard-of-hearing (alias)"></i>',
    HASHTAG = '<i class="fa fa-hashtag"></i>',
    HDD_O = '<i class="fa fa-hdd-o"></i>',
    HEADER = '<i class="fa fa-header"></i>',
    HEADPHONES = '<i class="fa fa-headphones"></i>',
    HEART = '<i class="fa fa-heart"></i>',
    HEART_O = '<i class="fa fa-heart-o"></i>',
    HEARTBEAT = '<i class="fa fa-heartbeat"></i>',
    HISTORY = '<i class="fa fa-history"></i>',
    HOME = '<i class="fa fa-home"></i>',
    HOSPITAL_O = '<i class="fa fa-hospital-o"></i>',
    HOTEL = '<i class="fa fa-hotel (alias)"></i>',
    HOURGLASS = '<i class="fa fa-hourglass"></i>',
    HOURGLASS_1 = '<i class="fa fa-hourglass-1 (alias)"></i>',
    HOURGLASS_2 = '<i class="fa fa-hourglass-2 (alias)"></i>',
    HOURGLASS_3 = '<i class="fa fa-hourglass-3 (alias)"></i>',
    HOURGLASS_END = '<i class="fa fa-hourglass-end"></i>',
    HOURGLASS_HALF = '<i class="fa fa-hourglass-half"></i>',
    HOURGLASS_O = '<i class="fa fa-hourglass-o"></i>',
    HOURGLASS_START = '<i class="fa fa-hourglass-start"></i>',
    HOUZZ = '<i class="fa fa-houzz"></i>',
    HTML5 = '<i class="fa fa-html5"></i>',
    I_CURSOR = '<i class="fa fa-i-cursor"></i>',
    ID_BADGE = '<i class="fa fa-id-badge"></i>',
    ID_CARD = '<i class="fa fa-id-card"></i>',
    ID_CARD_O = '<i class="fa fa-id-card-o"></i>',
    ILS = '<i class="fa fa-ils"></i>',
    IMAGE = '<i class="fa fa-image (alias)"></i>',
    IMDB = '<i class="fa fa-imdb"></i>',
    INBOX = '<i class="fa fa-inbox"></i>',
    INDENT = '<i class="fa fa-indent"></i>',
    INDUSTRY = '<i class="fa fa-industry"></i>',
    INFO = '<i class="fa fa-info"></i>',
    INFO_CIRCLE = '<i class="fa fa-info-circle"></i>',
    INR = '<i class="fa fa-inr"></i>',
    INSTAGRAM = '<i class="fa fa-instagram"></i>',
    INSTITUTION = '<i class="fa fa-institution (alias)"></i>',
    INTERNET_EXPLORER = '<i class="fa fa-internet-explorer"></i>',
    INTERSEX = '<i class="fa fa-intersex (alias)"></i>',
    IOXHOST = '<i class="fa fa-ioxhost"></i>',
    ITALIC = '<i class="fa fa-italic"></i>',
    JOOMLA = '<i class="fa fa-joomla"></i>',
    JPY = '<i class="fa fa-jpy"></i>',
    JSFIDDLE = '<i class="fa fa-jsfiddle"></i>',
    KEY = '<i class="fa fa-key"></i>',
    KEYBOARD_O = '<i class="fa fa-keyboard-o"></i>',
    KRW = '<i class="fa fa-krw"></i>',
    LANGUAGE = '<i class="fa fa-language"></i>',
    LAPTOP = '<i class="fa fa-laptop"></i>',
    LASTFM = '<i class="fa fa-lastfm"></i>',
    LASTFM_SQUARE = '<i class="fa fa-lastfm-square"></i>',
    LAYER_GROUP = '<i class="fa fa-layer-group"></i>',
    LEAF = '<i class="fa fa-leaf"></i>',
    LEANPUB = '<i class="fa fa-leanpub"></i>',
    LEGAL = '<i class="fa fa-legal (alias)"></i>',
    LEMON_O = '<i class="fa fa-lemon-o"></i>',
    LEVEL_DOWN = '<i class="fa fa-level-down"></i>',
    LEVEL_UP = '<i class="fa fa-level-up"></i>',
    LIFE_BOUY = '<i class="fa fa-life-bouy (alias)"></i>',
    LIFE_BUOY = '<i class="fa fa-life-buoy (alias)"></i>',
    LIFE_RING = '<i class="fa fa-life-ring"></i>',
    LIFE_SAVER = '<i class="fa fa-life-saver (alias)"></i>',
    LIGHTBULB_O = '<i class="fa fa-lightbulb-o"></i>',
    LINE_CHART = '<i class="fa fa-line-chart"></i>',
    LINK = '<i class="fa fa-link"></i>',
    LINKEDIN = '<i class="fa fa-linkedin"></i>',
    LINKEDIN_SQUARE = '<i class="fa fa-linkedin-square"></i>',
    LINODE = '<i class="fa fa-linode"></i>',
    LINUX = '<i class="fa fa-linux"></i>',
    LIST = '<i class="fa fa-list"></i>',
    LIST_ALT = '<i class="fa fa-list-alt"></i>',
    LIST_OL = '<i class="fa fa-list-ol"></i>',
    LIST_UL = '<i class="fa fa-list-ul"></i>',
    LOCATION_ARROW = '<i class="fa fa-location-arrow"></i>',
    LOCK = '<i class="fa fa-lock"></i>',
    LONG_ARROW_DOWN = '<i class="fa fa-long-arrow-down"></i>',
    LONG_ARROW_LEFT = '<i class="fa fa-long-arrow-left"></i>',
    LONG_ARROW_RIGHT = '<i class="fa fa-long-arrow-right"></i>',
    LONG_ARROW_UP = '<i class="fa fa-long-arrow-up"></i>',
    LOW_VISION = '<i class="fa fa-low-vision"></i>',
    MAGIC = '<i class="fa fa-magic"></i>',
    MAGNET = '<i class="fa fa-magnet"></i>',
    MAIL_FORWARD = '<i class="fa fa-mail-forward (alias)"></i>',
    MAIL_REPLY = '<i class="fa fa-mail-reply (alias)"></i>',
    MAIL_REPLY_ALL = '<i class="fa fa-mail-reply-all (alias)"></i>',
    MALE = '<i class="fa fa-male"></i>',
    MAP = '<i class="fa fa-map"></i>',
    MAP_MARKER = '<i class="fa fa-map-marker"></i>',
    MAP_O = '<i class="fa fa-map-o"></i>',
    MAP_PIN = '<i class="fa fa-map-pin"></i>',
    MAP_SIGNS = '<i class="fa fa-map-signs"></i>',
    MARS = '<i class="fa fa-mars"></i>',
    MARS_DOUBLE = '<i class="fa fa-mars-double"></i>',
    MARS_STROKE = '<i class="fa fa-mars-stroke"></i>',
    MARS_STROKE_H = '<i class="fa fa-mars-stroke-h"></i>',
    MARS_STROKE_V = '<i class="fa fa-mars-stroke-v"></i>',
    MAXCDN = '<i class="fa fa-maxcdn"></i>',
    MEANPATH = '<i class="fa fa-meanpath"></i>',
    MEDIUM = '<i class="fa fa-medium"></i>',
    MEDKIT = '<i class="fa fa-medkit"></i>',
    MEETUP = '<i class="fa fa-meetup"></i>',
    MEH_O = '<i class="fa fa-meh-o"></i>',
    MERCURY = '<i class="fa fa-mercury"></i>',
    MICROCHIP = '<i class="fa fa-microchip"></i>',
    MICROPHONE = '<i class="fa fa-microphone"></i>',
    MICROPHONE_SLASH = '<i class="fa fa-microphone-slash"></i>',
    MINUS = '<i class="fa fa-minus"></i>',
    MINUS_CIRCLE = '<i class="fa fa-minus-circle"></i>',
    MINUS_SQUARE = '<i class="fa fa-minus-square"></i>',
    MINUS_SQUARE_O = '<i class="fa fa-minus-square-o"></i>',
    MIXCLOUD = '<i class="fa fa-mixcloud"></i>',
    MOBILE = '<i class="fa fa-mobile"></i>',
    MOBILE_PHONE = '<i class="fa fa-mobile-phone (alias)"></i>',
    MODX = '<i class="fa fa-modx"></i>',
    MONEY = '<i class="fa fa-money"></i>',
    MOON_O = '<i class="fa fa-moon-o"></i>',
    MORTAR_BOARD = '<i class="fa fa-mortar-board (alias)"></i>',
    MOTORCYCLE = '<i class="fa fa-motorcycle"></i>',
    MOUSE_POINTER = '<i class="fa fa-mouse-pointer"></i>',
    MUSIC = '<i class="fa fa-music"></i>',
    NAVICON = '<i class="fa fa-navicon (alias)"></i>',
    NEUTER = '<i class="fa fa-neuter"></i>',
    NEWSPAPER_O = '<i class="fa fa-newspaper-o"></i>',
    OBJECT_GROUP = '<i class="fa fa-object-group"></i>',
    OBJECT_UNGROUP = '<i class="fa fa-object-ungroup"></i>',
    ODNOKLASSNIKI = '<i class="fa fa-odnoklassniki"></i>',
    ODNOKLASSNIKI_SQUARE = '<i class="fa fa-odnoklassniki-square"></i>',
    OPENCART = '<i class="fa fa-opencart"></i>',
    OPENID = '<i class="fa fa-openid"></i>',
    OPERA = '<i class="fa fa-opera"></i>',
    OPTIN_MONSTER = '<i class="fa fa-optin-monster"></i>',
    OUTDENT = '<i class="fa fa-outdent"></i>',
    PAGELINES = '<i class="fa fa-pagelines"></i>',
    PAINT_BRUSH = '<i class="fa fa-paint-brush"></i>',
    PAPER_PLANE = '<i class="fa fa-paper-plane"></i>',
    PAPER_PLANE_O = '<i class="fa fa-paper-plane-o"></i>',
    PAPERCLIP = '<i class="fa fa-paperclip"></i>',
    PARAGRAPH = '<i class="fa fa-paragraph"></i>',
    PASTE = '<i class="fa fa-paste (alias)"></i>',
    PAUSE = '<i class="fa fa-pause"></i>',
    PAUSE_CIRCLE = '<i class="fa fa-pause-circle"></i>',
    PAUSE_CIRCLE_O = '<i class="fa fa-pause-circle-o"></i>',
    PAW = '<i class="fa fa-paw"></i>',
    PAYPAL = '<i class="fa fa-paypal"></i>',
    PENCIL = '<i class="fa fa-pencil"></i>',
    PENCIL_SQUARE = '<i class="fa fa-pencil-square"></i>',
    PENCIL_SQUARE_O = '<i class="fa fa-pencil-square-o"></i>',
    PERCENT = '<i class="fa fa-percent"></i>',
    PHONE = '<i class="fa fa-phone"></i>',
    PHONE_SQUARE = '<i class="fa fa-phone-square"></i>',
    PHOTO = '<i class="fa fa-photo (alias)"></i>',
    PICTURE_O = '<i class="fa fa-picture-o"></i>',
    PIE_CHART = '<i class="fa fa-pie-chart"></i>',
    PIED_PIPER = '<i class="fa fa-pied-piper"></i>',
    PIED_PIPER_ALT = '<i class="fa fa-pied-piper-alt"></i>',
    PIED_PIPER_PP = '<i class="fa fa-pied-piper-pp"></i>',
    PINTEREST = '<i class="fa fa-pinterest"></i>',
    PINTEREST_P = '<i class="fa fa-pinterest-p"></i>',
    PINTEREST_SQUARE = '<i class="fa fa-pinterest-square"></i>',
    PLANE = '<i class="fa fa-plane"></i>',
    PLAY = '<i class="fa fa-play"></i>',
    PLAY_CIRCLE = '<i class="fa fa-play-circle"></i>',
    PLAY_CIRCLE_O = '<i class="fa fa-play-circle-o"></i>',
    PLUG = '<i class="fa fa-plug"></i>',
    PLUS = '<i class="fa fa-plus"></i>',
    PLUS_CIRCLE = '<i class="fa fa-plus-circle"></i>',
    PLUS_SQUARE = '<i class="fa fa-plus-square"></i>',
    PLUS_SQUARE_O = '<i class="fa fa-plus-square-o"></i>',
    PODCAST = '<i class="fa fa-podcast"></i>',
    POWER_OFF = '<i class="fa fa-power-off"></i>',
    PRINT = '<i class="fa fa-print"></i>',
    PRODUCT_HUNT = '<i class="fa fa-product-hunt"></i>',
    PUZZLE_PIECE = '<i class="fa fa-puzzle-piece"></i>',
    QQ = '<i class="fa fa-qq"></i>',
    QRCODE = '<i class="fa fa-qrcode"></i>',
    QUESTION = '<i class="fa fa-question"></i>',
    QUESTION_CIRCLE = '<i class="fa fa-question-circle"></i>',
    QUESTION_CIRCLE_O = '<i class="fa fa-question-circle-o"></i>',
    QUORA = '<i class="fa fa-quora"></i>',
    QUOTE_LEFT = '<i class="fa fa-quote-left"></i>',
    QUOTE_RIGHT = '<i class="fa fa-quote-right"></i>',
    RA = '<i class="fa fa-ra (alias)"></i>',
    RANDOM = '<i class="fa fa-random"></i>',
    RAVELRY = '<i class="fa fa-ravelry"></i>',
    REBEL = '<i class="fa fa-rebel"></i>',
    RECYCLE = '<i class="fa fa-recycle"></i>',
    REDDIT = '<i class="fa fa-reddit"></i>',
    REDDIT_ALIEN = '<i class="fa fa-reddit-alien"></i>',
    REDDIT_SQUARE = '<i class="fa fa-reddit-square"></i>',
    REFRESH = '<i class="fa fa-refresh"></i>',
    REGISTERED = '<i class="fa fa-registered"></i>',
    REMOVE = '<i class="fa fa-remove (alias)"></i>',
    RENREN = '<i class="fa fa-renren"></i>',
    REORDER = '<i class="fa fa-reorder (alias)"></i>',
    REPEAT = '<i class="fa fa-repeat"></i>',
    REPLY = '<i class="fa fa-reply"></i>',
    REPLY_ALL = '<i class="fa fa-reply-all"></i>',
    RESISTANCE = '<i class="fa fa-resistance (alias)"></i>',
    RETWEET = '<i class="fa fa-retweet"></i>',
    RMB = '<i class="fa fa-rmb (alias)"></i>',
    ROAD = '<i class="fa fa-road"></i>',
    ROCKET = '<i class="fa fa-rocket"></i>',
    ROTATE_LEFT = '<i class="fa fa-rotate-left (alias)"></i>',
    ROTATE_RIGHT = '<i class="fa fa-rotate-right (alias)"></i>',
    ROUBLE = '<i class="fa fa-rouble (alias)"></i>',
    RSS = '<i class="fa fa-rss"></i>',
    RSS_SQUARE = '<i class="fa fa-rss-square"></i>',
    RUB = '<i class="fa fa-rub"></i>',
    RUBLE = '<i class="fa fa-ruble (alias)"></i>',
    RUPEE = '<i class="fa fa-rupee (alias)"></i>',
    S15 = '<i class="fa fa-s15 (alias)"></i>',
    SAFARI = '<i class="fa fa-safari"></i>',
    SAVE = '<i class="fa fa-save (alias)"></i>',
    SCISSORS = '<i class="fa fa-scissors"></i>',
    SCRIBD = '<i class="fa fa-scribd"></i>',
    SEARCH = '<i class="fa fa-search"></i>',
    SEARCH_MINUS = '<i class="fa fa-search-minus"></i>',
    SEARCH_PLUS = '<i class="fa fa-search-plus"></i>',
    SELLSY = '<i class="fa fa-sellsy"></i>',
    SEND = '<i class="fa fa-send (alias)"></i>',
    SEND_O = '<i class="fa fa-send-o (alias)"></i>',
    SERVER = '<i class="fa fa-server"></i>',
    SHARE = '<i class="fa fa-share"></i>',
    SHARE_ALT = '<i class="fa fa-share-alt"></i>',
    SHARE_ALT_SQUARE = '<i class="fa fa-share-alt-square"></i>',
    SHARE_SQUARE = '<i class="fa fa-share-square"></i>',
    SHARE_SQUARE_O = '<i class="fa fa-share-square-o"></i>',
    SHEKEL = '<i class="fa fa-shekel (alias)"></i>',
    SHEQEL = '<i class="fa fa-sheqel (alias)"></i>',
    SHIELD = '<i class="fa fa-shield"></i>',
    SHIP = '<i class="fa fa-ship"></i>',
    SHIRTSINBULK = '<i class="fa fa-shirtsinbulk"></i>',
    SHOPPING_BAG = '<i class="fa fa-shopping-bag"></i>',
    SHOPPING_BASKET = '<i class="fa fa-shopping-basket"></i>',
    SHOPPING_CART = '<i class="fa fa-shopping-cart"></i>',
    SHOWER = '<i class="fa fa-shower"></i>',
    SIGN_IN = '<i class="fa fa-sign-in"></i>',
    SIGN_LANGUAGE = '<i class="fa fa-sign-language"></i>',
    SIGN_OUT = '<i class="fa fa-sign-out"></i>',
    SIGNAL = '<i class="fa fa-signal"></i>',
    SIGNING = '<i class="fa fa-signing (alias)"></i>',
    SIMPLYBUILT = '<i class="fa fa-simplybuilt"></i>',
    SITEMAP = '<i class="fa fa-sitemap"></i>',
    SKYATLAS = '<i class="fa fa-skyatlas"></i>',
    SKYPE = '<i class="fa fa-skype"></i>',
    SLACK = '<i class="fa fa-slack"></i>',
    SLIDERS = '<i class="fa fa-sliders"></i>',
    SLIDESHARE = '<i class="fa fa-slideshare"></i>',
    SMILE_O = '<i class="fa fa-smile-o"></i>',
    SNAPCHAT = '<i class="fa fa-snapchat"></i>',
    SNAPCHAT_GHOST = '<i class="fa fa-snapchat-ghost"></i>',
    SNAPCHAT_SQUARE = '<i class="fa fa-snapchat-square"></i>',
    SNOWFLAKE_O = '<i class="fa fa-snowflake-o"></i>',
    SOCCER_BALL_O = '<i class="fa fa-soccer-ball-o (alias)"></i>',
    SORT = '<i class="fa fa-sort"></i>',
    SORT_ALPHA_ASC = '<i class="fa fa-sort-alpha-asc"></i>',
    SORT_ALPHA_DESC = '<i class="fa fa-sort-alpha-desc"></i>',
    SORT_AMOUNT_ASC = '<i class="fa fa-sort-amount-asc"></i>',
    SORT_AMOUNT_DESC = '<i class="fa fa-sort-amount-desc"></i>',
    SORT_ASC = '<i class="fa fa-sort-asc"></i>',
    SORT_DESC = '<i class="fa fa-sort-desc"></i>',
    SORT_DOWN = '<i class="fa fa-sort-down (alias)"></i>',
    SORT_NUMERIC_ASC = '<i class="fa fa-sort-numeric-asc"></i>',
    SORT_NUMERIC_DESC = '<i class="fa fa-sort-numeric-desc"></i>',
    SORT_UP = '<i class="fa fa-sort-up (alias)"></i>',
    SOUNDCLOUD = '<i class="fa fa-soundcloud"></i>',
    SPACE_SHUTTLE = '<i class="fa fa-space-shuttle"></i>',
    SPINNER = '<i class="fa fa-spinner"></i>',
    SPOON = '<i class="fa fa-spoon"></i>',
    SPOTIFY = '<i class="fa fa-spotify"></i>',
    SQUARE = '<i class="fa fa-square"></i>',
    SQUARE_O = '<i class="fa fa-square-o"></i>',
    STACK_EXCHANGE = '<i class="fa fa-stack-exchange"></i>',
    STACK_OVERFLOW = '<i class="fa fa-stack-overflow"></i>',
    STAR = '<i class="fa fa-star"></i>',
    STAR_HALF = '<i class="fa fa-star-half"></i>',
    STAR_HALF_EMPTY = '<i class="fa fa-star-half-empty (alias)"></i>',
    STAR_HALF_FULL = '<i class="fa fa-star-half-full (alias)"></i>',
    STAR_HALF_O = '<i class="fa fa-star-half-o"></i>',
    STAR_O = '<i class="fa fa-star-o"></i>',
    STEAM = '<i class="fa fa-steam"></i>',
    STEAM_SQUARE = '<i class="fa fa-steam-square"></i>',
    STEP_BACKWARD = '<i class="fa fa-step-backward"></i>',
    STEP_FORWARD = '<i class="fa fa-step-forward"></i>',
    STETHOSCOPE = '<i class="fa fa-stethoscope"></i>',
    STICKY_NOTE = '<i class="fa fa-sticky-note"></i>',
    STICKY_NOTE_O = '<i class="fa fa-sticky-note-o"></i>',
    STOP = '<i class="fa fa-stop"></i>',
    STOP_CIRCLE = '<i class="fa fa-stop-circle"></i>',
    STOP_CIRCLE_O = '<i class="fa fa-stop-circle-o"></i>',
    STREET_VIEW = '<i class="fa fa-street-view"></i>',
    STRIKETHROUGH = '<i class="fa fa-strikethrough"></i>',
    STUMBLEUPON = '<i class="fa fa-stumbleupon"></i>',
    STUMBLEUPON_CIRCLE = '<i class="fa fa-stumbleupon-circle"></i>',
    SUBSCRIPT = '<i class="fa fa-subscript"></i>',
    SUBWAY = '<i class="fa fa-subway"></i>',
    SUITCASE = '<i class="fa fa-suitcase"></i>',
    SUN_O = '<i class="fa fa-sun-o"></i>',
    SUPERPOWERS = '<i class="fa fa-superpowers"></i>',
    SUPERSCRIPT = '<i class="fa fa-superscript"></i>',
    SUPPORT = '<i class="fa fa-support (alias)"></i>',
    TABLE = '<i class="fa fa-table"></i>',
    TABLET = '<i class="fa fa-tablet"></i>',
    TACHOMETER = '<i class="fa fa-tachometer"></i>',
    TAG = '<i class="fa fa-tag"></i>',
    TAGS = '<i class="fa fa-tags"></i>',
    TASKS = '<i class="fa fa-tasks"></i>',
    TAXI = '<i class="fa fa-taxi"></i>',
    TELEGRAM = '<i class="fa fa-telegram"></i>',
    TELEVISION = '<i class="fa fa-television"></i>',
    TENCENT_WEIBO = '<i class="fa fa-tencent-weibo"></i>',
    TERMINAL = '<i class="fa fa-terminal"></i>',
    TEXT_HEIGHT = '<i class="fa fa-text-height"></i>',
    TEXT_WIDTH = '<i class="fa fa-text-width"></i>',
    TH = '<i class="fa fa-th"></i>',
    TH_LARGE = '<i class="fa fa-th-large"></i>',
    TH_LIST = '<i class="fa fa-th-list"></i>',
    THEMEISLE = '<i class="fa fa-themeisle"></i>',
    THERMOMETER = '<i class="fa fa-thermometer (alias)"></i>',
    THERMOMETER_0 = '<i class="fa fa-thermometer-0 (alias)"></i>',
    THERMOMETER_1 = '<i class="fa fa-thermometer-1 (alias)"></i>',
    THERMOMETER_2 = '<i class="fa fa-thermometer-2 (alias)"></i>',
    THERMOMETER_3 = '<i class="fa fa-thermometer-3 (alias)"></i>',
    THERMOMETER_4 = '<i class="fa fa-thermometer-4 (alias)"></i>',
    THERMOMETER_EMPTY = '<i class="fa fa-thermometer-empty"></i>',
    THERMOMETER_FULL = '<i class="fa fa-thermometer-full"></i>',
    THERMOMETER_HALF = '<i class="fa fa-thermometer-half"></i>',
    THERMOMETER_QUARTER = '<i class="fa fa-thermometer-quarter"></i>',
    THERMOMETER_THREE_QUARTERS = '<i class="fa fa-thermometer-three-quarters"></i>',
    THUMB_TACK = '<i class="fa fa-thumb-tack"></i>',
    THUMBS_DOWN = '<i class="fa fa-thumbs-down"></i>',
    THUMBS_O_DOWN = '<i class="fa fa-thumbs-o-down"></i>',
    THUMBS_O_UP = '<i class="fa fa-thumbs-o-up"></i>',
    THUMBS_UP = '<i class="fa fa-thumbs-up"></i>',
    TICKET = '<i class="fa fa-ticket"></i>',
    TIMES = '<i class="fa fa-times"></i>',
    TIMES_CIRCLE = '<i class="fa fa-times-circle"></i>',
    TIMES_CIRCLE_O = '<i class="fa fa-times-circle-o"></i>',
    TIMES_RECTANGLE = '<i class="fa fa-times-rectangle (alias)"></i>',
    TIMES_RECTANGLE_O = '<i class="fa fa-times-rectangle-o (alias)"></i>',
    TINT = '<i class="fa fa-tint"></i>',
    TOGGLE_DOWN = '<i class="fa fa-toggle-down (alias)"></i>',
    TOGGLE_LEFT = '<i class="fa fa-toggle-left (alias)"></i>',
    TOGGLE_OFF = '<i class="fa fa-toggle-off"></i>',
    TOGGLE_ON = '<i class="fa fa-toggle-on"></i>',
    TOGGLE_RIGHT = '<i class="fa fa-toggle-right (alias)"></i>',
    TOGGLE_UP = '<i class="fa fa-toggle-up (alias)"></i>',
    TRADEMARK = '<i class="fa fa-trademark"></i>',
    TRAIN = '<i class="fa fa-train"></i>',
    TRANSGENDER = '<i class="fa fa-transgender"></i>',
    TRANSGENDER_ALT = '<i class="fa fa-transgender-alt"></i>',
    TRASH = '<i class="fa fa-trash"></i>',
    TRASH_O = '<i class="fa fa-trash-o"></i>',
    TREE = '<i class="fa fa-tree"></i>',
    TRELLO = '<i class="fa fa-trello"></i>',
    TRIPADVISOR = '<i class="fa fa-tripadvisor"></i>',
    TROPHY = '<i class="fa fa-trophy"></i>',
    TRUCK = '<i class="fa fa-truck"></i>',
    TRY = '<i class="fa fa-try"></i>',
    TTY = '<i class="fa fa-tty"></i>',
    TUMBLR = '<i class="fa fa-tumblr"></i>',
    TUMBLR_SQUARE = '<i class="fa fa-tumblr-square"></i>',
    TURKISH_LIRA = '<i class="fa fa-turkish-lira (alias)"></i>',
    TV = '<i class="fa fa-tv (alias)"></i>',
    TWITCH = '<i class="fa fa-twitch"></i>',
    TWITTER = '<i class="fa fa-twitter"></i>',
    TWITTER_SQUARE = '<i class="fa fa-twitter-square"></i>',
    UMBRELLA = '<i class="fa fa-umbrella"></i>',
    UNDERLINE = '<i class="fa fa-underline"></i>',
    UNDO = '<i class="fa fa-undo"></i>',
    UNIVERSAL_ACCESS = '<i class="fa fa-universal-access"></i>',
    UNIVERSITY = '<i class="fa fa-university"></i>',
    UNLINK = '<i class="fa fa-unlink (alias)"></i>',
    UNLOCK = '<i class="fa fa-unlock"></i>',
    UNLOCK_ALT = '<i class="fa fa-unlock-alt"></i>',
    UNSORTED = '<i class="fa fa-unsorted (alias)"></i>',
    UPLOAD = '<i class="fa fa-upload"></i>',
    USB = '<i class="fa fa-usb"></i>',
    USD = '<i class="fa fa-usd"></i>',
    USER = '<i class="fa fa-user"></i>',
    USER_CIRCLE = '<i class="fa fa-user-circle"></i>',
    USER_CIRCLE_O = '<i class="fa fa-user-circle-o"></i>',
    USER_MD = '<i class="fa fa-user-md"></i>',
    USER_O = '<i class="fa fa-user-o"></i>',
    USER_PLUS = '<i class="fa fa-user-plus"></i>',
    USER_SECRET = '<i class="fa fa-user-secret"></i>',
    USER_TIMES = '<i class="fa fa-user-times"></i>',
    USERS = '<i class="fa fa-users"></i>',
    VCARD = '<i class="fa fa-vcard (alias)"></i>',
    VCARD_O = '<i class="fa fa-vcard-o (alias)"></i>',
    VENUS = '<i class="fa fa-venus"></i>',
    VENUS_DOUBLE = '<i class="fa fa-venus-double"></i>',
    VENUS_MARS = '<i class="fa fa-venus-mars"></i>',
    VIACOIN = '<i class="fa fa-viacoin"></i>',
    VIADEO = '<i class="fa fa-viadeo"></i>',
    VIADEO_SQUARE = '<i class="fa fa-viadeo-square"></i>',
    VIDEO_CAMERA = '<i class="fa fa-video-camera"></i>',
    VIMEO = '<i class="fa fa-vimeo"></i>',
    VIMEO_SQUARE = '<i class="fa fa-vimeo-square"></i>',
    VINE = '<i class="fa fa-vine"></i>',
    VK = '<i class="fa fa-vk"></i>',
    VOLUME_CONTROL_PHONE = '<i class="fa fa-volume-control-phone"></i>',
    VOLUME_DOWN = '<i class="fa fa-volume-down"></i>',
    VOLUME_OFF = '<i class="fa fa-volume-off"></i>',
    VOLUME_UP = '<i class="fa fa-volume-up"></i>',
    WARNING = '<i class="fa fa-warning (alias)"></i>',
    WECHAT = '<i class="fa fa-wechat (alias)"></i>',
    WEIBO = '<i class="fa fa-weibo"></i>',
    WEIXIN = '<i class="fa fa-weixin"></i>',
    WHATSAPP = '<i class="fa fa-whatsapp"></i>',
    WHEELCHAIR = '<i class="fa fa-wheelchair"></i>',
    WHEELCHAIR_ALT = '<i class="fa fa-wheelchair-alt"></i>',
    WIFI = '<i class="fa fa-wifi"></i>',
    WIKIPEDIA_W = '<i class="fa fa-wikipedia-w"></i>',
    WINDOW_CLOSE = '<i class="fa fa-window-close"></i>',
    WINDOW_CLOSE_O = '<i class="fa fa-window-close-o"></i>',
    WINDOW_MAXIMIZE = '<i class="fa fa-window-maximize"></i>',
    WINDOW_MINIMIZE = '<i class="fa fa-window-minimize"></i>',
    WINDOW_RESTORE = '<i class="fa fa-window-restore"></i>',
    WINDOWS = '<i class="fa fa-windows"></i>',
    WON = '<i class="fa fa-won (alias)"></i>',
    WORDPRESS = '<i class="fa fa-wordpress"></i>',
    WPBEGINNER = '<i class="fa fa-wpbeginner"></i>',
    WPEXPLORER = '<i class="fa fa-wpexplorer"></i>',
    WPFORMS = '<i class="fa fa-wpforms"></i>',
    WRENCH = '<i class="fa fa-wrench"></i>',
    XING = '<i class="fa fa-xing"></i>',
    XING_SQUARE = '<i class="fa fa-xing-square"></i>',
    Y_COMBINATOR = '<i class="fa fa-y-combinator"></i>',
    Y_COMBINATOR_SQUARE = '<i class="fa fa-y-combinator-square (alias)"></i>',
    YAHOO = '<i class="fa fa-yahoo"></i>',
    YC = '<i class="fa fa-yc (alias)"></i>',
    YC_SQUARE = '<i class="fa fa-yc-square (alias)"></i>',
    YELP = '<i class="fa fa-yelp"></i>',
    YEN = '<i class="fa fa-yen (alias)"></i>',
    YOAST = '<i class="fa fa-yoast"></i>',
    YOUTUBE = '<i class="fa fa-youtube"></i>',
    YOUTUBE_PLAY = '<i class="fa fa-youtube-play"></i>',
    YOUTUBE_SQUARE = '<i class="fa fa-youtube-square"></i>'



}